(define (pascals-triangle height)
  (define (pascals-triangle-level level)
    (define (number-on-level level position)
      (if (or (= position 0) (= position level))
          1
          (+ (number-on-level (- level 1) position) (number-on-level (- level 1) (- position 1)))))
    (define (position-iteration cur-position)
      (display (number-on-level level cur-position))
      (cond ((< cur-position level) (display " ")
                                    (position-iteration (+ cur-position 1)))))
    (position-iteration 0) (newline))
  (define (level-iteration cur-level)
    (cond ((< cur-level height) (pascals-triangle-level cur-level)
                                (level-iteration (+ cur-level 1)))))
  (level-iteration 0))
